--DEPT 抛捞喉 积己
CREATE TABLE DEPT (
  DEPTNO NUMBER NOT NULL PRIMARY KEY
, DNAME VARCHAR2(14 BYTE) 
, LOC VARCHAR2(13 BYTE) 
); 

--EMP 抛捞喉 积己
CREATE TABLE EMP
(
  EMPNO NUMBER NOT NULL PRIMARY KEY
, ENAME VARCHAR2(10 BYTE)
, JOB VARCHAR2(9 BYTE)
, MGR NUMBER
, HIREDATE DATE
, SAL NUMBER
, COMM NUMBER
, DEPTNO NUMBER NOT NULL
);

--EMPLIST 积己
CREATE VIEW EMPLIST
AS SELECT 
    EMPNO, ENAME, JOB, DNAME
FROM 
    EMP, DEPT
WHERE 
    EMP.DEPTNO=DEPT.DEPTNO;
