CREATE VIEW EMPLIST
AS SELECT 
    EMPNO,ENAME,JOB,DNAME
FROM 
    EMP, DEPT
WHERE
    EMP.DEPTNO = DEPT.DEPTNO;
    
CREATE TABLE EMP 
(
  EMPNO NUMBER NOT NULL 
, ENAME VARCHAR2(10 BYTE) 
, JOB VARCHAR2(9 BYTE) 
, MGR NUMBER 
, HIREDATE DATE 
, SAL NUMBER 
, COMM NUMBER 
, DEPTNO VARCHAR2(20 BYTE) 
, CONSTRAINT EMP_PK PRIMARY KEY 
  (
    EMPNO 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX EMP_PK ON EMP (EMPNO ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLEL;

ALTER TABLE EMP
ADD CONSTRAINT EMP_FK1 FOREIGN KEY
(
  EMPNO 
)
REFERENCES DEPT
(
  DEPTNO 
)
ENABLE;
