CREATE TABLE EMP 
(
  EMPNO NUMBER NOT NULL PRIMARY key
, ENAME NVARCHAR2(10) 
, JOB VARCHAR2(9 BYTE) 
, MGR NUMBER 
, HIREDATE DATE 
, SAL NUMBER 
, COMM NUMBER 
, DEPTNO NUMBER NOT NULL 
);
--EMP.deptno 에 FOREIGN KEY 설정
ALTER TABLE EMP
ADD CONSTRAINT EMP_FK1 FOREIGN KEY
(
  DEPTNO 
)
REFERENCES DEPT
(
  DEPTNO 
)
ENABLE;
-- EMPLIST View 생성

CREATE VIEW EMPLIST
AS SELECT 
    empno ,ename,job,dname
FROM 
    emp , dept
where
    emp.deptno=dept.deptno;

  