CREATE TABLE DEPT 
(
  DEPTNO NUMBER NOT NULL PRIMARY KEY 
, DNAME VARCHAR2(14) 
, LOC VARCHAR2(13)  
);

CREATE TABLE EMP 
(
  EMPNO NUMBER NOT NULL PRIMARY KEY
, ENAME VARCHAR2(10 BYTE) 
, JOB VARCHAR2(9 BYTE) 
, MGR NUMBER 
, HIREDATE DATE 
, SAL NUMBER 
, COMM NUMBER 
, DEPTNO NUMBER NOT NULL 
);

ALTER TABLE EMP
ADD CONSTRAINT EMP_FK1 FOREIGN KEY
(
  DEPTNO 
)
REFERENCES DEPT
(
  DEPTNO 
)
ENABLE;

CREATE VIEW EMPLIST
AS SELECT 
    empno, ename, job,dname
FROM 
    emp, dept
where
    emp.deptno=dept.deptno;