DROP TABLE EMP;
DROP TABLE DEPT;

CREATE TABLE DEPT (
  DEPTNO NUMBER NOT NULL PRIMARY KEY
, DNAME VARCHAR2(14) 
, LOC VARCHAR2(13) 
); 

CREATE TABLE EMP(
  EMPNO NUMBER NOT NULL PRIMARY KEY
, ENAME VARCHAR2(10) 
, JOB VARCHAR2(9) 
, MGR NUMBER 
, HIREDATE DATE 
, SAL NUMBER 
, COMM NUMBER 
, DEPTNO VARCHAR2(20) 
);

CREATE VIEW EMPLIST
AS SELECT 
    EMPNO, ENAME, JOB, DNAME
FROM 
    EMP E, DEPT D
WHERE 
    E.DEPTNO=D.DEPTNO;

