CREATE TABLE TEST(
NO NUMBER NOT NULL 
, NAME VARCHAR2(20) 
, SAL NUMBER);

DESC TEST;

INSERT INTO TEST VALUES(1,'차승원',2000);
INSERT INTO TEST(NO,NAME,SAL) VALUES(2,'유해진',2500);
INSERT INTO TEST(NO,NAME,SAL) VALUES(3,'손호준',1500);

SELECT * FROM TEST;

UPDATE TEST SET SAL=2500 WHERE NO=1;

SELECT * FROM TEST WHERE SAL<2000;

UPDATE TEST SET SAL=3000 WHERE SAL>=2000;
SELECT * FROM TEST;

DELETE FROM TEST;

COMMIT;